### ISSUE TITLE
Media is downloaded successfully(Visible in app) BUT videos and images are not coming into the gallery, I tried to check the folder which is supposed to be created but the folder is not present.

### ISSUE THREAD

**Issue by NomanBaigA** [KishanViramgama/InstagramDownloader#10]
- Tested in android 9 device and android 11 emulator
- Thanks for resolving the old issue. I hope you will resolve this too quickly

**Comment by KishanViramgama** [comment]
@NomanBaigA Image and video storing inside package name that's why not showing in gallery

**Comment by NomanBaigA** [comment]
> @NomanBaigA Image and video storing inside package name that's why not showing in gallery

- Yes, But from the user's point of view, it should come in the gallery
- Because after downloading an image or video user first check this in the gallery

**Comment by KishanViramgama** [comment]
@NomanBaigA Right now not showing download image in the gallery section but you can easily customization your own. I will try to implement in next update.

**Comment by NomanBaigA** [comment]
> @NomanBaigA Right now not showing download image in the gallery section but you can easily customization your own. I will try to implement in next update.

Sure I will try. Thanks :)
