### ISSUE TITLE
Downloading Issue

### ISSUE THREAD

**Issue by zeeshan0022** [KishanViramgama/InstagramDownloader#11]
Work only under Mobile internet now under wifi

**Comment by KishanViramgama** [comment]
@zeeshan0022 it works perfectly with WIFI connection. May be some firewall issue

**Comment by zeeshan0022** [comment]
@KishanViramgama Maybe.. Its Saying Http 401 error

**Comment by KishanViramgama** [comment]
@zeeshan0022 Okay only public post supported.

**Comment by zeeshan0022** [comment]
its public ..but when i download using wifi its denied but in mobile net its works with same link

**Comment by KishanViramgama** [comment]
@zeeshan0022 Okay i will check

**Comment by zeeshan0022** [comment]
Yes I can show you video

**Comment by zeeshan0022** [comment]
https://user-images.githubusercontent.com/42519518/212551549-32f472f1-11d6-4583-8ede-a30e42ebbd25.mp4

**Comment by zeeshan0022** [comment]
https://user-images.githubusercontent.com/42519518/212551587-28e0c90e-de61-4961-b438-7d81dc1b8081.mp4

**Comment by KishanViramgama** [comment]
@zeeshan0022 Okay i will check as soon as possible 😊

**Comment by zeeshan0022** [comment]
Ok bro thank you

**Comment by KishanViramgama** [comment]
@zeeshan0022 Please check update code. and check with your WiFi
