### ISSUE TITLE
JCenter has been sunsetted, and many libraries have moved to Maven Central

### ISSUE THREAD

**Issue by AndroidWithRossyn** [KishanViramgama/InstagramDownloader#19]
**JCenter** is not working anymore, I saw your project.
I want to contribute to your project.
Can we build these dependencies using a manual setup?

-> Failed to resolve: io.github.lizhangqu:coreprogress:1.0.2
-> Failed to resolve: com.romandanylyk:pageindicatorview:1.0.3

**Comment by KishanViramgama** [comment]
@AndroidWithRossyn I will resolve this issue as soon as possible.
