### ISSUE TITLE
App is not working

### ISSUE THREAD

**Issue by KishorKokate** [KishanViramgama/InstagramDownloader#2]

**Comment by KishanViramgama** [comment]
Provide more information @KishorKokate

**Comment by salman-apk** [comment]
brother, it shows a "Not Supported" error upon following the instructions and pasting an image post link into the URL section. 
My Device: Android 12

**Comment by KishanViramgama** [comment]
@salman660 Only working on public profile post download. Not working on private profile.

**Comment by KishanViramgama** [comment]
@KishorKokate @salman660 
- Please check out new version
- Right now only public post download supported

**Comment by salman-apk** [comment]
Brother I checked the recent **_Demo.apk_**, At first it opened fine and i clicked on the Instagram icon opening it right from the app. Copied a link of _image_ post and pasted it in app then clicked on the _submit button_, the app crashed right after. I can provide you with the screen recording as well if required.
 

_Android 12 Version_

**Comment by KishanViramgama** [comment]
Okay I will check with android 12 version

**Comment by KishanViramgama** [comment]
@salman660 please checkout issue solved
