### ISSUE TITLE
W/System.err: org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by nikhilgodhani08** [KishanViramgama/InstagramDownloader#4]
I download your code and run in android studio.
and i try download instagram reels and images .
but it's not working.
it's showing error

W/System.err: org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

you have any solution ?
please send me .

**Comment by KishanViramgama** [comment]
@nikhil888-teach 

- Only public post download 
- Please send me like which reels you are download. I am check the error

**Comment by nikhilgodhani08** [comment]
https://www.instagram.com/p/Ce2I6uXpHUU/?utm_source=ig_web_copy_link

I run Program in My Samsung device
but it's still getting error 
W/System.err: org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

**Comment by KishanViramgama** [comment]
@nikhil888-teach Worked properly open this link in Instagram application and copy link this post.

**Comment by nikhilgodhani08** [comment]
when i run your program in emulator than it's working but i run in my Samsung device then it's not working

I try last 3-4 days but it's not working


which device you use for run program?

**Comment by KishanViramgama** [comment]
Nokia 6.1 plus

**Comment by nikhilgodhani08** [comment]
https://www.instagram.com/p/Ce2I6uXpHUU/?utm_source=ig_web_copy_link

I paste this link but it's not supported

![image](https://user-images.githubusercontent.com/84656107/174031778-ee1d3d7c-bfdf-4c95-9b50-4a0a5aa864e3.png)

![image](https://user-images.githubusercontent.com/84656107/174031858-1aec7a25-dd71-46f4-80e8-cd1ec59ecc32.png)

**Comment by KishanViramgama** [comment]
Ok I will check as soon as possible

**Comment by nikhilgodhani08** [comment]
ok

**Comment by nikhilgodhani08** [comment]
you find any solution?
I need this solution

**Comment by KishanViramgama** [comment]
Right now I am not working this library but as soon as possible the find out the solution.

**Comment by nikhilgodhani08** [comment]
ok

**Comment by nikhilgodhani08** [comment]
any solution ?

**Comment by nikhilgodhani08** [comment]
Hey you find any solution ?

**Comment by KishanViramgama** [comment]
@nikhil888-teach 
- Please check out new version
- Right now only public post download supported
