### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Chintu800** [KishanViramgama/InstagramDownloader#7]
Any solution???

**Comment by KishanViramgama** [comment]
@Chintu800 Please provide more information about your issue. This repository only working on public post download load.

**Comment by Chintu800** [comment]
sir Your apk also not working

**Comment by Chintu800** [comment]
https://www.youtube.com/watch?v=QkEQ0SmF3bY&list=PLOgVpbPIyEj31MK0IZvBAE3f6JTzZ9lye&index=5

i also watched this video and follow all steps and seens last finally data
is not fetching for json

**Comment by KishanViramgama** [comment]
This video is a not part of this repository

**Comment by NomanBaigA** [comment]
> This video is a not part of this repository

I tried your app from the play store also but it's not working properly. sometimes it crashed

**Comment by KishanViramgama** [comment]
Ok I will check. please provide Instagram post link then I will investigate about this issue deeply.

**Comment by NomanBaigA** [comment]
> Ok I will check. please provide Instagram post link then I will investigate about this issue deeply.

Just try any link from a search. this is working with normal posts but not with reels so please test it with reels

**Comment by KishanViramgama** [comment]
Ok I will check  as soon as possible

**Comment by KishanViramgama** [comment]
@NomanBaigA and @Chintu800 
- Please check out new version
- Right now only public post download supported
