### ISSUE TITLE
Is it possible to get downloaded items in Gallery?

### ISSUE THREAD

**Issue by yogeshjangid** [KishanViramgama/InstagramDownloader#9]
Hi Kishan Bhai,

Thank you for making this project and glad you have submitted on Github.

I've a simple but technical question. Is it possible to get downloaded items in Gallery, As I tried to change "download_folder_path" but it's showing under the shared folder which is creating by the app only.

If possible kindly assist me with this, rest of all other functions and app is working superb.

![image](https://user-images.githubusercontent.com/318610/209292219-201c53f6-e6e3-4d19-a5dc-6decd4388995.png)

**Comment by KishanViramgama** [comment]
@yogeshjangid Yes it's is possible check out android official storage document.
